// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.32.0
// 	protoc        v4.25.1
// source: pkg/pb/user-compliance.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateUserRecord
type CreateUserRecordRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreateUserRecordRequest) Reset() {
	*x = CreateUserRecordRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_user_compliance_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserRecordRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRecordRequest) ProtoMessage() {}

func (x *CreateUserRecordRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_user_compliance_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRecordRequest.ProtoReflect.Descriptor instead.
func (*CreateUserRecordRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_user_compliance_proto_rawDescGZIP(), []int{0}
}

type CreateUserRecordResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *CreateUserRecordResponse) Reset() {
	*x = CreateUserRecordResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_user_compliance_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserRecordResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserRecordResponse) ProtoMessage() {}

func (x *CreateUserRecordResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_user_compliance_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserRecordResponse.ProtoReflect.Descriptor instead.
func (*CreateUserRecordResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_user_compliance_proto_rawDescGZIP(), []int{1}
}

func (x *CreateUserRecordResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// SetIdentityVerified
type SetIdentityVerifiedRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LinkSessionId string `protobuf:"bytes,1,opt,name=linkSessionId,proto3" json:"linkSessionId,omitempty"`
}

func (x *SetIdentityVerifiedRequest) Reset() {
	*x = SetIdentityVerifiedRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_user_compliance_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetIdentityVerifiedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetIdentityVerifiedRequest) ProtoMessage() {}

func (x *SetIdentityVerifiedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_user_compliance_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetIdentityVerifiedRequest.ProtoReflect.Descriptor instead.
func (*SetIdentityVerifiedRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_user_compliance_proto_rawDescGZIP(), []int{2}
}

func (x *SetIdentityVerifiedRequest) GetLinkSessionId() string {
	if x != nil {
		return x.LinkSessionId
	}
	return ""
}

type SetIdentityVerifiedResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsVerified bool `protobuf:"varint,1,opt,name=isVerified,proto3" json:"isVerified,omitempty"`
}

func (x *SetIdentityVerifiedResponse) Reset() {
	*x = SetIdentityVerifiedResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_user_compliance_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SetIdentityVerifiedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetIdentityVerifiedResponse) ProtoMessage() {}

func (x *SetIdentityVerifiedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_user_compliance_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetIdentityVerifiedResponse.ProtoReflect.Descriptor instead.
func (*SetIdentityVerifiedResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_user_compliance_proto_rawDescGZIP(), []int{3}
}

func (x *SetIdentityVerifiedResponse) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

// IsIdentityVerified
type GetAccountStatusRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetAccountStatusRequest) Reset() {
	*x = GetAccountStatusRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_user_compliance_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAccountStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountStatusRequest) ProtoMessage() {}

func (x *GetAccountStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_user_compliance_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountStatusRequest.ProtoReflect.Descriptor instead.
func (*GetAccountStatusRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_user_compliance_proto_rawDescGZIP(), []int{4}
}

type GetAccountStatusResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IsVerified            bool `protobuf:"varint,1,opt,name=isVerified,proto3" json:"isVerified,omitempty"`
	GalileoAccountCreated bool `protobuf:"varint,2,opt,name=GalileoAccountCreated,proto3" json:"GalileoAccountCreated,omitempty"`
}

func (x *GetAccountStatusResponse) Reset() {
	*x = GetAccountStatusResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_user_compliance_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetAccountStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAccountStatusResponse) ProtoMessage() {}

func (x *GetAccountStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_user_compliance_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAccountStatusResponse.ProtoReflect.Descriptor instead.
func (*GetAccountStatusResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_user_compliance_proto_rawDescGZIP(), []int{5}
}

func (x *GetAccountStatusResponse) GetIsVerified() bool {
	if x != nil {
		return x.IsVerified
	}
	return false
}

func (x *GetAccountStatusResponse) GetGalileoAccountCreated() bool {
	if x != nil {
		return x.GalileoAccountCreated
	}
	return false
}

// GetUserPRN
type GetUserPRNRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId string `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
}

func (x *GetUserPRNRequest) Reset() {
	*x = GetUserPRNRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_user_compliance_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserPRNRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPRNRequest) ProtoMessage() {}

func (x *GetUserPRNRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_user_compliance_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPRNRequest.ProtoReflect.Descriptor instead.
func (*GetUserPRNRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_user_compliance_proto_rawDescGZIP(), []int{6}
}

func (x *GetUserPRNRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetUserPRNResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Prn string `protobuf:"bytes,1,opt,name=prn,proto3" json:"prn,omitempty"`
}

func (x *GetUserPRNResponse) Reset() {
	*x = GetUserPRNResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_user_compliance_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserPRNResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserPRNResponse) ProtoMessage() {}

func (x *GetUserPRNResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_user_compliance_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserPRNResponse.ProtoReflect.Descriptor instead.
func (*GetUserPRNResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_user_compliance_proto_rawDescGZIP(), []int{7}
}

func (x *GetUserPRNResponse) GetPrn() string {
	if x != nil {
		return x.Prn
	}
	return ""
}

// UpdateUserAccount
type UpdateUserAccountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username     string        `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	PersonalInfo *PersonalInfo `protobuf:"bytes,2,opt,name=personalInfo,proto3" json:"personalInfo,omitempty"`
	Address      *Address      `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *UpdateUserAccountRequest) Reset() {
	*x = UpdateUserAccountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_user_compliance_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUserAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserAccountRequest) ProtoMessage() {}

func (x *UpdateUserAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_user_compliance_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserAccountRequest.ProtoReflect.Descriptor instead.
func (*UpdateUserAccountRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_user_compliance_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateUserAccountRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UpdateUserAccountRequest) GetPersonalInfo() *PersonalInfo {
	if x != nil {
		return x.PersonalInfo
	}
	return nil
}

func (x *UpdateUserAccountRequest) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

type UpdateUserAccountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status             int64               `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error              string              `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Message            string              `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	GalileoAccountInfo *GalileoAccountInfo `protobuf:"bytes,4,opt,name=galileoAccountInfo,proto3" json:"galileoAccountInfo,omitempty"`
}

func (x *UpdateUserAccountResponse) Reset() {
	*x = UpdateUserAccountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_user_compliance_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UpdateUserAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateUserAccountResponse) ProtoMessage() {}

func (x *UpdateUserAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_user_compliance_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateUserAccountResponse.ProtoReflect.Descriptor instead.
func (*UpdateUserAccountResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_user_compliance_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateUserAccountResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *UpdateUserAccountResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *UpdateUserAccountResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *UpdateUserAccountResponse) GetGalileoAccountInfo() *GalileoAccountInfo {
	if x != nil {
		return x.GalileoAccountInfo
	}
	return nil
}

// GetUserProfile
type GetUserAccountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *GetUserAccountRequest) Reset() {
	*x = GetUserAccountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_user_compliance_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAccountRequest) ProtoMessage() {}

func (x *GetUserAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_user_compliance_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAccountRequest.ProtoReflect.Descriptor instead.
func (*GetUserAccountRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_user_compliance_proto_rawDescGZIP(), []int{10}
}

type GetUserAccountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UserId       string        `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Username     string        `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"`
	PersonalInfo *PersonalInfo `protobuf:"bytes,3,opt,name=personalInfo,proto3" json:"personalInfo,omitempty"`
	Address      *Address      `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *GetUserAccountResponse) Reset() {
	*x = GetUserAccountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_user_compliance_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetUserAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserAccountResponse) ProtoMessage() {}

func (x *GetUserAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_user_compliance_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserAccountResponse.ProtoReflect.Descriptor instead.
func (*GetUserAccountResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_user_compliance_proto_rawDescGZIP(), []int{11}
}

func (x *GetUserAccountResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GetUserAccountResponse) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *GetUserAccountResponse) GetPersonalInfo() *PersonalInfo {
	if x != nil {
		return x.PersonalInfo
	}
	return nil
}

func (x *GetUserAccountResponse) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

// CreateUserAccount
type CreateUserAccountRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Username string `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
}

func (x *CreateUserAccountRequest) Reset() {
	*x = CreateUserAccountRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_user_compliance_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserAccountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserAccountRequest) ProtoMessage() {}

func (x *CreateUserAccountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_user_compliance_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserAccountRequest.ProtoReflect.Descriptor instead.
func (*CreateUserAccountRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_user_compliance_proto_rawDescGZIP(), []int{12}
}

func (x *CreateUserAccountRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

type CreateUserAccountResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status                int64                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`
	Error                 string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	Message               string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	GalileoAccountStatus  string                 `protobuf:"bytes,4,opt,name=galileoAccountStatus,proto3" json:"galileoAccountStatus,omitempty"`
	GalileoAccountDetails *GalileoAccountDetails `protobuf:"bytes,5,opt,name=galileoAccountDetails,proto3" json:"galileoAccountDetails,omitempty"`
}

func (x *CreateUserAccountResponse) Reset() {
	*x = CreateUserAccountResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_user_compliance_proto_msgTypes[13]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateUserAccountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateUserAccountResponse) ProtoMessage() {}

func (x *CreateUserAccountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_user_compliance_proto_msgTypes[13]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateUserAccountResponse.ProtoReflect.Descriptor instead.
func (*CreateUserAccountResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_user_compliance_proto_rawDescGZIP(), []int{13}
}

func (x *CreateUserAccountResponse) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CreateUserAccountResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

func (x *CreateUserAccountResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *CreateUserAccountResponse) GetGalileoAccountStatus() string {
	if x != nil {
		return x.GalileoAccountStatus
	}
	return ""
}

func (x *CreateUserAccountResponse) GetGalileoAccountDetails() *GalileoAccountDetails {
	if x != nil {
		return x.GalileoAccountDetails
	}
	return nil
}

// Supporting message types
type Address struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Address1    string `protobuf:"bytes,1,opt,name=address1,proto3" json:"address1,omitempty"`
	Address2    string `protobuf:"bytes,2,opt,name=address2,proto3" json:"address2,omitempty"`
	City        string `protobuf:"bytes,3,opt,name=city,proto3" json:"city,omitempty"`
	State       string `protobuf:"bytes,4,opt,name=state,proto3" json:"state,omitempty"`
	PostalCode  string `protobuf:"bytes,5,opt,name=postalCode,proto3" json:"postalCode,omitempty"`
	CountryCode string `protobuf:"bytes,6,opt,name=countryCode,proto3" json:"countryCode,omitempty"`
}

func (x *Address) Reset() {
	*x = Address{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_user_compliance_proto_msgTypes[14]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Address) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Address) ProtoMessage() {}

func (x *Address) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_user_compliance_proto_msgTypes[14]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Address.ProtoReflect.Descriptor instead.
func (*Address) Descriptor() ([]byte, []int) {
	return file_pkg_pb_user_compliance_proto_rawDescGZIP(), []int{14}
}

func (x *Address) GetAddress1() string {
	if x != nil {
		return x.Address1
	}
	return ""
}

func (x *Address) GetAddress2() string {
	if x != nil {
		return x.Address2
	}
	return ""
}

func (x *Address) GetCity() string {
	if x != nil {
		return x.City
	}
	return ""
}

func (x *Address) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *Address) GetPostalCode() string {
	if x != nil {
		return x.PostalCode
	}
	return ""
}

func (x *Address) GetCountryCode() string {
	if x != nil {
		return x.CountryCode
	}
	return ""
}

type PersonalInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	FirstName   string                 `protobuf:"bytes,1,opt,name=firstName,proto3" json:"firstName,omitempty"`
	LastName    string                 `protobuf:"bytes,2,opt,name=lastName,proto3" json:"lastName,omitempty"`
	PhoneNumber string                 `protobuf:"bytes,3,opt,name=phoneNumber,proto3" json:"phoneNumber,omitempty"`
	Email       string                 `protobuf:"bytes,4,opt,name=email,proto3" json:"email,omitempty"`
	DateOfBirth *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=dateOfBirth,proto3" json:"dateOfBirth,omitempty"`
	Id          string                 `protobuf:"bytes,6,opt,name=id,proto3" json:"id,omitempty"`
	IdType      int32                  `protobuf:"varint,7,opt,name=idType,proto3" json:"idType,omitempty"`
}

func (x *PersonalInfo) Reset() {
	*x = PersonalInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_user_compliance_proto_msgTypes[15]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PersonalInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalInfo) ProtoMessage() {}

func (x *PersonalInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_user_compliance_proto_msgTypes[15]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalInfo.ProtoReflect.Descriptor instead.
func (*PersonalInfo) Descriptor() ([]byte, []int) {
	return file_pkg_pb_user_compliance_proto_rawDescGZIP(), []int{15}
}

func (x *PersonalInfo) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *PersonalInfo) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *PersonalInfo) GetPhoneNumber() string {
	if x != nil {
		return x.PhoneNumber
	}
	return ""
}

func (x *PersonalInfo) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *PersonalInfo) GetDateOfBirth() *timestamppb.Timestamp {
	if x != nil {
		return x.DateOfBirth
	}
	return nil
}

func (x *PersonalInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PersonalInfo) GetIdType() int32 {
	if x != nil {
		return x.IdType
	}
	return 0
}

type GalileoAccountDetails struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CardId           string `protobuf:"bytes,1,opt,name=cardId,proto3" json:"cardId,omitempty"`
	CardNumber       string `protobuf:"bytes,2,opt,name=cardNumber,proto3" json:"cardNumber,omitempty"`
	CardSecurityCode string `protobuf:"bytes,3,opt,name=cardSecurityCode,proto3" json:"cardSecurityCode,omitempty"`
}

func (x *GalileoAccountDetails) Reset() {
	*x = GalileoAccountDetails{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_user_compliance_proto_msgTypes[16]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GalileoAccountDetails) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GalileoAccountDetails) ProtoMessage() {}

func (x *GalileoAccountDetails) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_user_compliance_proto_msgTypes[16]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GalileoAccountDetails.ProtoReflect.Descriptor instead.
func (*GalileoAccountDetails) Descriptor() ([]byte, []int) {
	return file_pkg_pb_user_compliance_proto_rawDescGZIP(), []int{16}
}

func (x *GalileoAccountDetails) GetCardId() string {
	if x != nil {
		return x.CardId
	}
	return ""
}

func (x *GalileoAccountDetails) GetCardNumber() string {
	if x != nil {
		return x.CardNumber
	}
	return ""
}

func (x *GalileoAccountDetails) GetCardSecurityCode() string {
	if x != nil {
		return x.CardSecurityCode
	}
	return ""
}

type GalileoAccountInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Status       string        `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	Message      string        `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	PersonalInfo *PersonalInfo `protobuf:"bytes,3,opt,name=personalInfo,proto3" json:"personalInfo,omitempty"`
	Address      *Address      `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
}

func (x *GalileoAccountInfo) Reset() {
	*x = GalileoAccountInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_user_compliance_proto_msgTypes[17]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GalileoAccountInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GalileoAccountInfo) ProtoMessage() {}

func (x *GalileoAccountInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_user_compliance_proto_msgTypes[17]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GalileoAccountInfo.ProtoReflect.Descriptor instead.
func (*GalileoAccountInfo) Descriptor() ([]byte, []int) {
	return file_pkg_pb_user_compliance_proto_rawDescGZIP(), []int{17}
}

func (x *GalileoAccountInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GalileoAccountInfo) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GalileoAccountInfo) GetPersonalInfo() *PersonalInfo {
	if x != nil {
		return x.PersonalInfo
	}
	return nil
}

func (x *GalileoAccountInfo) GetAddress() *Address {
	if x != nil {
		return x.Address
	}
	return nil
}

// CreatePlaidLinkToken
type CreatePlaidLinkTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreatePlaidLinkTokenRequest) Reset() {
	*x = CreatePlaidLinkTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_user_compliance_proto_msgTypes[18]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlaidLinkTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlaidLinkTokenRequest) ProtoMessage() {}

func (x *CreatePlaidLinkTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_user_compliance_proto_msgTypes[18]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlaidLinkTokenRequest.ProtoReflect.Descriptor instead.
func (*CreatePlaidLinkTokenRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_user_compliance_proto_rawDescGZIP(), []int{18}
}

type CreatePlaidLinkTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	LinkToken string `protobuf:"bytes,1,opt,name=linkToken,proto3" json:"linkToken,omitempty"`
}

func (x *CreatePlaidLinkTokenResponse) Reset() {
	*x = CreatePlaidLinkTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_user_compliance_proto_msgTypes[19]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlaidLinkTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlaidLinkTokenResponse) ProtoMessage() {}

func (x *CreatePlaidLinkTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_user_compliance_proto_msgTypes[19]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlaidLinkTokenResponse.ProtoReflect.Descriptor instead.
func (*CreatePlaidLinkTokenResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_user_compliance_proto_rawDescGZIP(), []int{19}
}

func (x *CreatePlaidLinkTokenResponse) GetLinkToken() string {
	if x != nil {
		return x.LinkToken
	}
	return ""
}

type Institution struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *Institution) Reset() {
	*x = Institution{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_user_compliance_proto_msgTypes[20]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Institution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Institution) ProtoMessage() {}

func (x *Institution) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_user_compliance_proto_msgTypes[20]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Institution.ProtoReflect.Descriptor instead.
func (*Institution) Descriptor() ([]byte, []int) {
	return file_pkg_pb_user_compliance_proto_rawDescGZIP(), []int{20}
}

func (x *Institution) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Institution) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type Account struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id                 string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name               string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Mask               string `protobuf:"bytes,3,opt,name=mask,proto3" json:"mask,omitempty"`
	Subtype            string `protobuf:"bytes,4,opt,name=subtype,proto3" json:"subtype,omitempty"`
	Type               string `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	VerificationStatus string `protobuf:"bytes,6,opt,name=verification_status,json=verificationStatus,proto3" json:"verification_status,omitempty"`
}

func (x *Account) Reset() {
	*x = Account{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_user_compliance_proto_msgTypes[21]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_user_compliance_proto_msgTypes[21]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_pkg_pb_user_compliance_proto_rawDescGZIP(), []int{21}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Account) GetMask() string {
	if x != nil {
		return x.Mask
	}
	return ""
}

func (x *Account) GetSubtype() string {
	if x != nil {
		return x.Subtype
	}
	return ""
}

func (x *Account) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Account) GetVerificationStatus() string {
	if x != nil {
		return x.VerificationStatus
	}
	return ""
}

type PlaidMetadata struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Institution   *Institution `protobuf:"bytes,1,opt,name=institution,proto3" json:"institution,omitempty"`
	Accounts      []*Account   `protobuf:"bytes,2,rep,name=accounts,proto3" json:"accounts,omitempty"`
	LinkSessionId string       `protobuf:"bytes,3,opt,name=link_session_id,json=linkSessionId,proto3" json:"link_session_id,omitempty"`
}

func (x *PlaidMetadata) Reset() {
	*x = PlaidMetadata{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_user_compliance_proto_msgTypes[22]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlaidMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlaidMetadata) ProtoMessage() {}

func (x *PlaidMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_user_compliance_proto_msgTypes[22]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlaidMetadata.ProtoReflect.Descriptor instead.
func (*PlaidMetadata) Descriptor() ([]byte, []int) {
	return file_pkg_pb_user_compliance_proto_rawDescGZIP(), []int{22}
}

func (x *PlaidMetadata) GetInstitution() *Institution {
	if x != nil {
		return x.Institution
	}
	return nil
}

func (x *PlaidMetadata) GetAccounts() []*Account {
	if x != nil {
		return x.Accounts
	}
	return nil
}

func (x *PlaidMetadata) GetLinkSessionId() string {
	if x != nil {
		return x.LinkSessionId
	}
	return ""
}

// CreatePlaidAccessToken
type CreatePlaidAccessTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PublicToken string         `protobuf:"bytes,1,opt,name=publicToken,proto3" json:"publicToken,omitempty"`
	Metadata    *PlaidMetadata `protobuf:"bytes,2,opt,name=metadata,proto3" json:"metadata,omitempty"`
}

func (x *CreatePlaidAccessTokenRequest) Reset() {
	*x = CreatePlaidAccessTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_user_compliance_proto_msgTypes[23]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlaidAccessTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlaidAccessTokenRequest) ProtoMessage() {}

func (x *CreatePlaidAccessTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_user_compliance_proto_msgTypes[23]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlaidAccessTokenRequest.ProtoReflect.Descriptor instead.
func (*CreatePlaidAccessTokenRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_user_compliance_proto_rawDescGZIP(), []int{23}
}

func (x *CreatePlaidAccessTokenRequest) GetPublicToken() string {
	if x != nil {
		return x.PublicToken
	}
	return ""
}

func (x *CreatePlaidAccessTokenRequest) GetMetadata() *PlaidMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

type CreatePlaidAccessTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AccessToken string `protobuf:"bytes,1,opt,name=accessToken,proto3" json:"accessToken,omitempty"`
}

func (x *CreatePlaidAccessTokenResponse) Reset() {
	*x = CreatePlaidAccessTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_user_compliance_proto_msgTypes[24]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlaidAccessTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlaidAccessTokenResponse) ProtoMessage() {}

func (x *CreatePlaidAccessTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_user_compliance_proto_msgTypes[24]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlaidAccessTokenResponse.ProtoReflect.Descriptor instead.
func (*CreatePlaidAccessTokenResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_user_compliance_proto_rawDescGZIP(), []int{24}
}

func (x *CreatePlaidAccessTokenResponse) GetAccessToken() string {
	if x != nil {
		return x.AccessToken
	}
	return ""
}

// CreatePlaidIDVToken
type CreatePlaidIDVTokenRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *CreatePlaidIDVTokenRequest) Reset() {
	*x = CreatePlaidIDVTokenRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_user_compliance_proto_msgTypes[25]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlaidIDVTokenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlaidIDVTokenRequest) ProtoMessage() {}

func (x *CreatePlaidIDVTokenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_user_compliance_proto_msgTypes[25]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlaidIDVTokenRequest.ProtoReflect.Descriptor instead.
func (*CreatePlaidIDVTokenRequest) Descriptor() ([]byte, []int) {
	return file_pkg_pb_user_compliance_proto_rawDescGZIP(), []int{25}
}

type CreatePlaidIDVTokenResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	IdvToken string `protobuf:"bytes,1,opt,name=idvToken,proto3" json:"idvToken,omitempty"`
}

func (x *CreatePlaidIDVTokenResponse) Reset() {
	*x = CreatePlaidIDVTokenResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_pkg_pb_user_compliance_proto_msgTypes[26]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreatePlaidIDVTokenResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreatePlaidIDVTokenResponse) ProtoMessage() {}

func (x *CreatePlaidIDVTokenResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_pb_user_compliance_proto_msgTypes[26]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreatePlaidIDVTokenResponse.ProtoReflect.Descriptor instead.
func (*CreatePlaidIDVTokenResponse) Descriptor() ([]byte, []int) {
	return file_pkg_pb_user_compliance_proto_rawDescGZIP(), []int{26}
}

func (x *CreatePlaidIDVTokenResponse) GetIdvToken() string {
	if x != nil {
		return x.IdvToken
	}
	return ""
}

var File_pkg_pb_user_compliance_proto protoreflect.FileDescriptor

var file_pkg_pb_user_compliance_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x2f, 0x75, 0x73, 0x65, 0x72, 0x2d, 0x63, 0x6f,
	0x6d, 0x70, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e,
	0x75, 0x73, 0x65, 0x72, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x1a, 0x1f,
	0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f,
	0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22,
	0x19, 0x0a, 0x17, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x63,
	0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x34, 0x0a, 0x18, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65,
	0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65,
	0x22, 0x42, 0x0a, 0x1a, 0x53, 0x65, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x56,
	0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x24,
	0x0a, 0x0d, 0x6c, 0x69, 0x6e, 0x6b, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0d, 0x6c, 0x69, 0x6e, 0x6b, 0x53, 0x65, 0x73, 0x73, 0x69,
	0x6f, 0x6e, 0x49, 0x64, 0x22, 0x3d, 0x0a, 0x1b, 0x53, 0x65, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x73, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x69, 0x73, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x69, 0x65, 0x64, 0x22, 0x19, 0x0a, 0x17, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x70,
	0x0a, 0x18, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x69, 0x73,
	0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a,
	0x69, 0x73, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x12, 0x34, 0x0a, 0x15, 0x47, 0x61,
	0x6c, 0x69, 0x6c, 0x65, 0x6f, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61,
	0x74, 0x65, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x15, 0x47, 0x61, 0x6c, 0x69, 0x6c,
	0x65, 0x6f, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x64,
	0x22, 0x2b, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x52, 0x4e, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x22, 0x26, 0x0a,
	0x12, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x52, 0x4e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x72, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x03, 0x70, 0x72, 0x6e, 0x22, 0xab, 0x01, 0x0a, 0x18, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x40,
	0x0a, 0x0c, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x63, 0x6f, 0x6d, 0x70, 0x6c,
	0x69, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x6e,
	0x66, 0x6f, 0x52, 0x0c, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f,
	0x12, 0x31, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x17, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x69, 0x61, 0x6e,
	0x63, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72,
	0x65, 0x73, 0x73, 0x22, 0xb7, 0x01, 0x0a, 0x19, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73,
	0x65, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x03, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72,
	0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12,
	0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x52, 0x0a, 0x12, 0x67, 0x61, 0x6c,
	0x69, 0x6c, 0x65, 0x6f, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x22, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x63, 0x6f, 0x6d, 0x70,
	0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x47, 0x61, 0x6c, 0x69, 0x6c, 0x65, 0x6f, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x12, 0x67, 0x61, 0x6c, 0x69, 0x6c,
	0x65, 0x6f, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x22, 0x17, 0x0a,
	0x15, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0xc1, 0x01, 0x0a, 0x16, 0x47, 0x65, 0x74, 0x55, 0x73,
	0x65, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x40, 0x0a, 0x0c, 0x70, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61,
	0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x50, 0x65, 0x72,
	0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x70, 0x65, 0x72, 0x73, 0x6f,
	0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x31, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65,
	0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x63,
	0x6f, 0x6d, 0x70, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x41, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x36, 0x0a, 0x18, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61,
	0x6d, 0x65, 0x22, 0xf4, 0x01, 0x0a, 0x19, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x72, 0x72, 0x6f,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x32, 0x0a, 0x14, 0x67, 0x61, 0x6c, 0x69,
	0x6c, 0x65, 0x6f, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x14, 0x67, 0x61, 0x6c, 0x69, 0x6c, 0x65, 0x6f, 0x41,
	0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x5b, 0x0a, 0x15,
	0x67, 0x61, 0x6c, 0x69, 0x6c, 0x65, 0x6f, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x44, 0x65,
	0x74, 0x61, 0x69, 0x6c, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x25, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x47, 0x61, 0x6c,
	0x69, 0x6c, 0x65, 0x6f, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69,
	0x6c, 0x73, 0x52, 0x15, 0x67, 0x61, 0x6c, 0x69, 0x6c, 0x65, 0x6f, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x22, 0xad, 0x01, 0x0a, 0x07, 0x41, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x31, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x31, 0x12, 0x1a, 0x0a, 0x08, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x32, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x08, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x32, 0x12, 0x12, 0x0a,
	0x04, 0x63, 0x69, 0x74, 0x79, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x63, 0x69, 0x74,
	0x79, 0x12, 0x14, 0x0a, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x73, 0x74, 0x61, 0x74, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x70, 0x6f, 0x73, 0x74, 0x61,
	0x6c, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x70, 0x6f, 0x73,
	0x74, 0x61, 0x6c, 0x43, 0x6f, 0x64, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x63, 0x6f, 0x75, 0x6e, 0x74,
	0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x63, 0x6f,
	0x75, 0x6e, 0x74, 0x72, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x22, 0xe6, 0x01, 0x0a, 0x0c, 0x50, 0x65,
	0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x1c, 0x0a, 0x09, 0x66, 0x69,
	0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x66,
	0x69, 0x72, 0x73, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x73, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x73, 0x74,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x68, 0x6f, 0x6e, 0x65,
	0x4e, 0x75, 0x6d, 0x62, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x18,
	0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x3c, 0x0a, 0x0b,
	0x64, 0x61, 0x74, 0x65, 0x4f, 0x66, 0x42, 0x69, 0x72, 0x74, 0x68, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1a, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x54, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x52, 0x0b, 0x64,
	0x61, 0x74, 0x65, 0x4f, 0x66, 0x42, 0x69, 0x72, 0x74, 0x68, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x64,
	0x54, 0x79, 0x70, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x69, 0x64, 0x54, 0x79,
	0x70, 0x65, 0x22, 0x7b, 0x0a, 0x15, 0x47, 0x61, 0x6c, 0x69, 0x6c, 0x65, 0x6f, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x44, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x63,
	0x61, 0x72, 0x64, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x61, 0x72,
	0x64, 0x49, 0x64, 0x12, 0x1e, 0x0a, 0x0a, 0x63, 0x61, 0x72, 0x64, 0x4e, 0x75, 0x6d, 0x62, 0x65,
	0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0a, 0x63, 0x61, 0x72, 0x64, 0x4e, 0x75, 0x6d,
	0x62, 0x65, 0x72, 0x12, 0x2a, 0x0a, 0x10, 0x63, 0x61, 0x72, 0x64, 0x53, 0x65, 0x63, 0x75, 0x72,
	0x69, 0x74, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x10, 0x63,
	0x61, 0x72, 0x64, 0x53, 0x65, 0x63, 0x75, 0x72, 0x69, 0x74, 0x79, 0x43, 0x6f, 0x64, 0x65, 0x22,
	0xbb, 0x01, 0x0a, 0x12, 0x47, 0x61, 0x6c, 0x69, 0x6c, 0x65, 0x6f, 0x41, 0x63, 0x63, 0x6f, 0x75,
	0x6e, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x12, 0x18,
	0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x40, 0x0a, 0x0c, 0x70, 0x65, 0x72, 0x73,
	0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1c,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x2e,
	0x50, 0x65, 0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x52, 0x0c, 0x70, 0x65,
	0x72, 0x73, 0x6f, 0x6e, 0x61, 0x6c, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x31, 0x0a, 0x07, 0x61, 0x64,
	0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x41, 0x64, 0x64,
	0x72, 0x65, 0x73, 0x73, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x1d, 0x0a,
	0x1b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x69, 0x64, 0x4c, 0x69, 0x6e, 0x6b,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x3c, 0x0a, 0x1c,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x69, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09,
	0x6c, 0x69, 0x6e, 0x6b, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x09, 0x6c, 0x69, 0x6e, 0x6b, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x22, 0x31, 0x0a, 0x0b, 0x49, 0x6e,
	0x73, 0x74, 0x69, 0x74, 0x75, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0xa0, 0x01,
	0x0a, 0x07, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a,
	0x04, 0x6d, 0x61, 0x73, 0x6b, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6d, 0x61, 0x73,
	0x6b, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x62, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x73, 0x75, 0x62, 0x74, 0x79, 0x70, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x74,
	0x79, 0x70, 0x65, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12,
	0x2f, 0x0a, 0x13, 0x76, 0x65, 0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x5f,
	0x73, 0x74, 0x61, 0x74, 0x75, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x12, 0x76, 0x65,
	0x72, 0x69, 0x66, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73,
	0x22, 0xab, 0x01, 0x0a, 0x0d, 0x50, 0x6c, 0x61, 0x69, 0x64, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x12, 0x3d, 0x0a, 0x0b, 0x69, 0x6e, 0x73, 0x74, 0x69, 0x74, 0x75, 0x74, 0x69, 0x6f,
	0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1b, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x63, 0x6f,
	0x6d, 0x70, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x49, 0x6e, 0x73, 0x74, 0x69, 0x74, 0x75,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x0b, 0x69, 0x6e, 0x73, 0x74, 0x69, 0x74, 0x75, 0x74, 0x69, 0x6f,
	0x6e, 0x12, 0x33, 0x0a, 0x08, 0x61, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x69,
	0x61, 0x6e, 0x63, 0x65, 0x2e, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x08, 0x61, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x73, 0x12, 0x26, 0x0a, 0x0f, 0x6c, 0x69, 0x6e, 0x6b, 0x5f, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0d, 0x6c, 0x69, 0x6e, 0x6b, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x22, 0x7c,
	0x0a, 0x1d, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x69, 0x64, 0x41, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x20, 0x0a, 0x0b, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x0b, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x39, 0x0a, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x69,
	0x61, 0x6e, 0x63, 0x65, 0x2e, 0x50, 0x6c, 0x61, 0x69, 0x64, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61,
	0x74, 0x61, 0x52, 0x08, 0x6d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0x22, 0x42, 0x0a, 0x1e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x69, 0x64, 0x41, 0x63, 0x63, 0x65, 0x73,
	0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x20,
	0x0a, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x22, 0x1c, 0x0a, 0x1a, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x69, 0x64, 0x49,
	0x44, 0x56, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x22, 0x39,
	0x0a, 0x1b, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x69, 0x64, 0x49, 0x44, 0x56,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1a, 0x0a,
	0x08, 0x69, 0x64, 0x76, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x69, 0x64, 0x76, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x32, 0xcf, 0x08, 0x0a, 0x15, 0x55, 0x73,
	0x65, 0x72, 0x43, 0x6f, 0x6d, 0x70, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x53, 0x65, 0x72, 0x76,
	0x69, 0x63, 0x65, 0x12, 0x6a, 0x0a, 0x11, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65,
	0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x28, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x63,
	0x6f, 0x6d, 0x70, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65,
	0x55, 0x73, 0x65, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x29, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x69, 0x61,
	0x6e, 0x63, 0x65, 0x2e, 0x55, 0x70, 0x64, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x41, 0x63,
	0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12,
	0x61, 0x0a, 0x0e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x12, 0x25, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x69, 0x61, 0x6e,
	0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x26, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x63,
	0x6f, 0x6d, 0x70, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65,
	0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x00, 0x12, 0x6a, 0x0a, 0x11, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x12, 0x28, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x63, 0x6f,
	0x6d, 0x70, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x29, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x69, 0x61, 0x6e,
	0x63, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x41, 0x63, 0x63,
	0x6f, 0x75, 0x6e, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x55,
	0x0a, 0x0a, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x52, 0x4e, 0x12, 0x21, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x47, 0x65,
	0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x52, 0x4e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x22, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65,
	0x2e, 0x47, 0x65, 0x74, 0x55, 0x73, 0x65, 0x72, 0x50, 0x52, 0x4e, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x67, 0x0a, 0x10, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55,
	0x73, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x12, 0x27, 0x2e, 0x75, 0x73, 0x65, 0x72,
	0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74,
	0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65, 0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x28, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x69, 0x61,
	0x6e, 0x63, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x55, 0x73, 0x65, 0x72, 0x52, 0x65,
	0x63, 0x6f, 0x72, 0x64, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x67,
	0x0a, 0x10, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74,
	0x75, 0x73, 0x12, 0x27, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x69, 0x61,
	0x6e, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x74,
	0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x28, 0x2e, 0x75, 0x73,
	0x65, 0x72, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x47, 0x65, 0x74,
	0x41, 0x63, 0x63, 0x6f, 0x75, 0x6e, 0x74, 0x53, 0x74, 0x61, 0x74, 0x75, 0x73, 0x52, 0x65, 0x73,
	0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x70, 0x0a, 0x13, 0x53, 0x65, 0x74, 0x49, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x12, 0x2a,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x2e,
	0x53, 0x65, 0x74, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x56, 0x65, 0x72, 0x69, 0x66,
	0x69, 0x65, 0x64, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x75, 0x73, 0x65,
	0x72, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x53, 0x65, 0x74, 0x49,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x56, 0x65, 0x72, 0x69, 0x66, 0x69, 0x65, 0x64, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x73, 0x0a, 0x14, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x69, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x2b, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x69, 0x61, 0x6e,
	0x63, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x69, 0x64, 0x4c, 0x69,
	0x6e, 0x6b, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2c,
	0x2e, 0x75, 0x73, 0x65, 0x72, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x2e,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x69, 0x64, 0x4c, 0x69, 0x6e, 0x6b, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x79,
	0x0a, 0x16, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x69, 0x64, 0x41, 0x63, 0x63,
	0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x2d, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x63,
	0x6f, 0x6d, 0x70, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65,
	0x50, 0x6c, 0x61, 0x69, 0x64, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2e, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x63, 0x6f,
	0x6d, 0x70, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50,
	0x6c, 0x61, 0x69, 0x64, 0x41, 0x63, 0x63, 0x65, 0x73, 0x73, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x12, 0x70, 0x0a, 0x13, 0x43, 0x72, 0x65,
	0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x69, 0x64, 0x49, 0x44, 0x56, 0x54, 0x6f, 0x6b, 0x65, 0x6e,
	0x12, 0x2a, 0x2e, 0x75, 0x73, 0x65, 0x72, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x69, 0x61, 0x6e, 0x63,
	0x65, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x69, 0x64, 0x49, 0x44, 0x56,
	0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x2b, 0x2e, 0x75,
	0x73, 0x65, 0x72, 0x63, 0x6f, 0x6d, 0x70, 0x6c, 0x69, 0x61, 0x6e, 0x63, 0x65, 0x2e, 0x43, 0x72,
	0x65, 0x61, 0x74, 0x65, 0x50, 0x6c, 0x61, 0x69, 0x64, 0x49, 0x44, 0x56, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x0a, 0x5a, 0x08, 0x2e,
	0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_pkg_pb_user_compliance_proto_rawDescOnce sync.Once
	file_pkg_pb_user_compliance_proto_rawDescData = file_pkg_pb_user_compliance_proto_rawDesc
)

func file_pkg_pb_user_compliance_proto_rawDescGZIP() []byte {
	file_pkg_pb_user_compliance_proto_rawDescOnce.Do(func() {
		file_pkg_pb_user_compliance_proto_rawDescData = protoimpl.X.CompressGZIP(file_pkg_pb_user_compliance_proto_rawDescData)
	})
	return file_pkg_pb_user_compliance_proto_rawDescData
}

var file_pkg_pb_user_compliance_proto_msgTypes = make([]protoimpl.MessageInfo, 27)
var file_pkg_pb_user_compliance_proto_goTypes = []interface{}{
	(*CreateUserRecordRequest)(nil),        // 0: usercompliance.CreateUserRecordRequest
	(*CreateUserRecordResponse)(nil),       // 1: usercompliance.CreateUserRecordResponse
	(*SetIdentityVerifiedRequest)(nil),     // 2: usercompliance.SetIdentityVerifiedRequest
	(*SetIdentityVerifiedResponse)(nil),    // 3: usercompliance.SetIdentityVerifiedResponse
	(*GetAccountStatusRequest)(nil),        // 4: usercompliance.GetAccountStatusRequest
	(*GetAccountStatusResponse)(nil),       // 5: usercompliance.GetAccountStatusResponse
	(*GetUserPRNRequest)(nil),              // 6: usercompliance.GetUserPRNRequest
	(*GetUserPRNResponse)(nil),             // 7: usercompliance.GetUserPRNResponse
	(*UpdateUserAccountRequest)(nil),       // 8: usercompliance.UpdateUserAccountRequest
	(*UpdateUserAccountResponse)(nil),      // 9: usercompliance.UpdateUserAccountResponse
	(*GetUserAccountRequest)(nil),          // 10: usercompliance.GetUserAccountRequest
	(*GetUserAccountResponse)(nil),         // 11: usercompliance.GetUserAccountResponse
	(*CreateUserAccountRequest)(nil),       // 12: usercompliance.CreateUserAccountRequest
	(*CreateUserAccountResponse)(nil),      // 13: usercompliance.CreateUserAccountResponse
	(*Address)(nil),                        // 14: usercompliance.Address
	(*PersonalInfo)(nil),                   // 15: usercompliance.PersonalInfo
	(*GalileoAccountDetails)(nil),          // 16: usercompliance.GalileoAccountDetails
	(*GalileoAccountInfo)(nil),             // 17: usercompliance.GalileoAccountInfo
	(*CreatePlaidLinkTokenRequest)(nil),    // 18: usercompliance.CreatePlaidLinkTokenRequest
	(*CreatePlaidLinkTokenResponse)(nil),   // 19: usercompliance.CreatePlaidLinkTokenResponse
	(*Institution)(nil),                    // 20: usercompliance.Institution
	(*Account)(nil),                        // 21: usercompliance.Account
	(*PlaidMetadata)(nil),                  // 22: usercompliance.PlaidMetadata
	(*CreatePlaidAccessTokenRequest)(nil),  // 23: usercompliance.CreatePlaidAccessTokenRequest
	(*CreatePlaidAccessTokenResponse)(nil), // 24: usercompliance.CreatePlaidAccessTokenResponse
	(*CreatePlaidIDVTokenRequest)(nil),     // 25: usercompliance.CreatePlaidIDVTokenRequest
	(*CreatePlaidIDVTokenResponse)(nil),    // 26: usercompliance.CreatePlaidIDVTokenResponse
	(*timestamppb.Timestamp)(nil),          // 27: google.protobuf.Timestamp
}
var file_pkg_pb_user_compliance_proto_depIdxs = []int32{
	15, // 0: usercompliance.UpdateUserAccountRequest.personalInfo:type_name -> usercompliance.PersonalInfo
	14, // 1: usercompliance.UpdateUserAccountRequest.address:type_name -> usercompliance.Address
	17, // 2: usercompliance.UpdateUserAccountResponse.galileoAccountInfo:type_name -> usercompliance.GalileoAccountInfo
	15, // 3: usercompliance.GetUserAccountResponse.personalInfo:type_name -> usercompliance.PersonalInfo
	14, // 4: usercompliance.GetUserAccountResponse.address:type_name -> usercompliance.Address
	16, // 5: usercompliance.CreateUserAccountResponse.galileoAccountDetails:type_name -> usercompliance.GalileoAccountDetails
	27, // 6: usercompliance.PersonalInfo.dateOfBirth:type_name -> google.protobuf.Timestamp
	15, // 7: usercompliance.GalileoAccountInfo.personalInfo:type_name -> usercompliance.PersonalInfo
	14, // 8: usercompliance.GalileoAccountInfo.address:type_name -> usercompliance.Address
	20, // 9: usercompliance.PlaidMetadata.institution:type_name -> usercompliance.Institution
	21, // 10: usercompliance.PlaidMetadata.accounts:type_name -> usercompliance.Account
	22, // 11: usercompliance.CreatePlaidAccessTokenRequest.metadata:type_name -> usercompliance.PlaidMetadata
	8,  // 12: usercompliance.UserComplianceService.UpdateUserAccount:input_type -> usercompliance.UpdateUserAccountRequest
	10, // 13: usercompliance.UserComplianceService.GetUserAccount:input_type -> usercompliance.GetUserAccountRequest
	12, // 14: usercompliance.UserComplianceService.CreateUserAccount:input_type -> usercompliance.CreateUserAccountRequest
	6,  // 15: usercompliance.UserComplianceService.GetUserPRN:input_type -> usercompliance.GetUserPRNRequest
	0,  // 16: usercompliance.UserComplianceService.CreateUserRecord:input_type -> usercompliance.CreateUserRecordRequest
	4,  // 17: usercompliance.UserComplianceService.GetAccountStatus:input_type -> usercompliance.GetAccountStatusRequest
	2,  // 18: usercompliance.UserComplianceService.SetIdentityVerified:input_type -> usercompliance.SetIdentityVerifiedRequest
	18, // 19: usercompliance.UserComplianceService.CreatePlaidLinkToken:input_type -> usercompliance.CreatePlaidLinkTokenRequest
	23, // 20: usercompliance.UserComplianceService.CreatePlaidAccessToken:input_type -> usercompliance.CreatePlaidAccessTokenRequest
	25, // 21: usercompliance.UserComplianceService.CreatePlaidIDVToken:input_type -> usercompliance.CreatePlaidIDVTokenRequest
	9,  // 22: usercompliance.UserComplianceService.UpdateUserAccount:output_type -> usercompliance.UpdateUserAccountResponse
	11, // 23: usercompliance.UserComplianceService.GetUserAccount:output_type -> usercompliance.GetUserAccountResponse
	13, // 24: usercompliance.UserComplianceService.CreateUserAccount:output_type -> usercompliance.CreateUserAccountResponse
	7,  // 25: usercompliance.UserComplianceService.GetUserPRN:output_type -> usercompliance.GetUserPRNResponse
	1,  // 26: usercompliance.UserComplianceService.CreateUserRecord:output_type -> usercompliance.CreateUserRecordResponse
	5,  // 27: usercompliance.UserComplianceService.GetAccountStatus:output_type -> usercompliance.GetAccountStatusResponse
	3,  // 28: usercompliance.UserComplianceService.SetIdentityVerified:output_type -> usercompliance.SetIdentityVerifiedResponse
	19, // 29: usercompliance.UserComplianceService.CreatePlaidLinkToken:output_type -> usercompliance.CreatePlaidLinkTokenResponse
	24, // 30: usercompliance.UserComplianceService.CreatePlaidAccessToken:output_type -> usercompliance.CreatePlaidAccessTokenResponse
	26, // 31: usercompliance.UserComplianceService.CreatePlaidIDVToken:output_type -> usercompliance.CreatePlaidIDVTokenResponse
	22, // [22:32] is the sub-list for method output_type
	12, // [12:22] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_pkg_pb_user_compliance_proto_init() }
func file_pkg_pb_user_compliance_proto_init() {
	if File_pkg_pb_user_compliance_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_pkg_pb_user_compliance_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserRecordRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_user_compliance_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserRecordResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_user_compliance_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetIdentityVerifiedRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_user_compliance_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SetIdentityVerifiedResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_user_compliance_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAccountStatusRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_user_compliance_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetAccountStatusResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_user_compliance_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserPRNRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_user_compliance_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserPRNResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_user_compliance_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateUserAccountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_user_compliance_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UpdateUserAccountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_user_compliance_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserAccountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_user_compliance_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetUserAccountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_user_compliance_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserAccountRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_user_compliance_proto_msgTypes[13].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateUserAccountResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_user_compliance_proto_msgTypes[14].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Address); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_user_compliance_proto_msgTypes[15].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PersonalInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_user_compliance_proto_msgTypes[16].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GalileoAccountDetails); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_user_compliance_proto_msgTypes[17].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GalileoAccountInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_user_compliance_proto_msgTypes[18].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePlaidLinkTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_user_compliance_proto_msgTypes[19].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePlaidLinkTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_user_compliance_proto_msgTypes[20].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Institution); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_user_compliance_proto_msgTypes[21].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Account); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_user_compliance_proto_msgTypes[22].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlaidMetadata); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_user_compliance_proto_msgTypes[23].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePlaidAccessTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_user_compliance_proto_msgTypes[24].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePlaidAccessTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_user_compliance_proto_msgTypes[25].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePlaidIDVTokenRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_pkg_pb_user_compliance_proto_msgTypes[26].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreatePlaidIDVTokenResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_pkg_pb_user_compliance_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   27,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_pb_user_compliance_proto_goTypes,
		DependencyIndexes: file_pkg_pb_user_compliance_proto_depIdxs,
		MessageInfos:      file_pkg_pb_user_compliance_proto_msgTypes,
	}.Build()
	File_pkg_pb_user_compliance_proto = out.File
	file_pkg_pb_user_compliance_proto_rawDesc = nil
	file_pkg_pb_user_compliance_proto_goTypes = nil
	file_pkg_pb_user_compliance_proto_depIdxs = nil
}
